# Generated by Django 6.0.6 on 2026-06-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='media/musics/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media/posts/'),
        ),
    ]
