# Generated by Django 6.0.6 on 2026-06-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposts',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos'),
        ),
        migrations.AlterField(
            model_name='savedvideos',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos'),
        ),
        migrations.AlterUniqueTogether(
            name='reposts',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='savedvideos',
            unique_together={('user', 'video')},
        ),
    ]
