# Generated by Django 6.0.6 on 2026-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_reposts_video_alter_savedvideos_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
