# Generated by Django 6.0.6 on 2026-06-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='in_actualnost',
        ),
        migrations.AddField(
            model_name='actualnost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='actualnost',
            name='stories',
        ),
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stories',
            name='file',
            field=models.FileField(upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualnost',
            name='stories',
            field=models.ManyToManyField(related_name='actualnost', to='stories.stories'),
        ),
    ]
