# Generated by Django 6.0.6 on 2026-06-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_stories_in_actualnost_actualnost_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='file',
            field=models.FileField(upload_to='media/stories/'),
        ),
    ]
